AllCops:
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - 'hackerrank_bot_saves_princess_1.rb'
    - 'hackerrank_bot_saves_princess_2.rb'

Layout/LineLength:
  Enabled: false
Layout/IndentationConsistency:
  Enabled: false
Layout/TrailingEmptyLines:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false
Style/Documentation:
  Enabled: false
Naming/MethodName:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
