# .circleci/config.yml
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.8
    steps:
      - checkout

      - run: ruby -v && gem -v

      - restore_cache:
          keys:
            - bundler-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - bundler-v1-{{ arch }}-{{ .Branch }}
            - bundler-v1

      - run:
          name: Install Bundler 2.4.22 & Gems
          command: |
            gem install bundler -v 2.4.22
            bundle _2.4.22_ config set path 'vendor/bundle'
            bundle _2.4.22_ install --jobs=4 --retry=3

      - save_cache:
          key: bundler-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Run tests
          command: |
            bundle _2.4.22_ exec rake spec

      - run:
          name: Run RuboCop
          command: |
            bundle _2.4.22_ exec rubocop

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
